[book]
title = "rsfdl Documentation"
authors = ["p0h12"]
language = "de"
src = "docs"

[build]
build-dir = "book"

[output.html]
default-theme = "rust"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/p0h12/rsfdl"
edit-url-template = "https://github.com/p0h12/rsfdl/edit/main/docs/{path}"
additional-css = ["assets/proto-reset.css"]
additional-js = ["assets/mermaid.min.js", "assets/mermaid-init.js", "assets/tailwind-cdn.js", "assets/proto-tabs.js"]

[preprocessor.mermaid]
command = "mdbook-mermaid"
